package org.jokes.entity;


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.NoArgsConstructor;
import lombok.ToString;


@Entity
@ToString
@NoArgsConstructor
@JsonIgnoreProperties(value = {"jokesid"}, allowGetters = true)

public class OfficialJokes {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long jokesid;  // Auto-generated by the database
    private Long id;
    private String type;
    private String setup;
    private String punchline;

    public OfficialJokes(Long id, String type, String setup, String punchline) {
        this.id = id;
        this.type = type;
        this.setup = setup;
        this.punchline = punchline;
    }

    public Long getJokesid() {
        return jokesid;
    }

    public void setJokesid(Long jokesid) {
        this.jokesid = jokesid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getSetup() {
        return setup;
    }

    public void setSetup(String setup) {
        this.setup = setup;
    }

    public String getPunchline() {
        return punchline;
    }

    public void setPunchline(String punchline) {
        this.punchline = punchline;
    }
}
